---
# https://github.com/NVIDIA/nvidia-docker

- name: Collect distribution detail
  set_fact:
     distribution: "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}"

- name: Add repository
  get_url:
    url: "https://nvidia.github.io/nvidia-docker/{{ distribution }}/nvidia-docker.repo"
    dest: /etc/yum.repos.d/nvidia-container.repo
    mode: '0644'

- name: install the latest version of the NVIDIA Container Toolkit
  yum:
    name: nvidia-container-toolkit
    state: latest
    update_cache: true
  notify:
    - restart docker
