---
# https://github.com/NVIDIA/nvidia-docker

- name: Collect distribution detail
  set_fact:
     distribution: "{{ ansible_distribution }}{{ ansible_distribution_version }}"

- name: Add repository
  yum_repository:
    name: nvidia-container
    description: NVIDIA Container toolkit repo
    baseurl: "https://nvidia.github.io/nvidia-docker/{{ distribution }}/nvidia-docker.repo"

- name: install the latest version of the NVIDIA Container Toolkit
  yum:
    name: nvidia-container-toolkit
    state: latest
  notify:
    - restart docker
